### ISSUE TITLE
GROUP.cfg not regarded when changing group

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#41] opened 2021-12-28 22:45 UTC
Hi there,

i whitnessed the following behavior (linbo 4.0.4)
Client in Group: focal got moved to Group semfocal.
It used to be that linbo used the ../boot/grub/GROUP.cfg from server on boot. Now the Behavior is different: the local .cfg is used so the Old config is used on boot, until the Client is partitioned (or a image is synced (i guess)).

Yours
Holger

**Comment by HappyBasher** [comment] 2021-12-29 17:50
I'm not able to reproduce that.
Procedure:
- change group of a client in devices.csv.
- run linuxmuster-import-devices.
- power on client.
- new group.cfg is used on client.

**Comment by baumhof** [comment] 2021-12-30 21:03
.. sorry: my Mistake.
I just figured out why the behavior was like this on my system: PXE boot does not work: local linbo is booting and will, of course, have the old grub.cfg...
sorry: forget the issue.

**Comment by HappyBasher** [comment] 2022-01-03 15:08
Please close the issue in future.

**Closed** 2022-01-03 15:07 UTC
